import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-center text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Congressional Bill Tracker
          </h1>
          <div>
            {user.isSignedIn && <SignOutButton />}
            {!user.isSignedIn && <SignInButton />}
          </div>

          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {data?.map((post) => (
                <div key={post.id}>
                  <p>{post.title}</p>
                  <p>{post.content}</p>
                </div>
              ))}
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
